CREATE TABLE `global_sender_id_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `messaging_provider` varchar(255) DEFAULT NULL,
  `business_name` varchar(255) DEFAULT NULL,
  `business_address` text DEFAULT NULL,
  `business_city_state` varchar(255) DEFAULT NULL,
  `business_zip` varchar(50) DEFAULT NULL,
  `contact_first_name` varchar(255) DEFAULT NULL,
  `contact_last_name` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_phone` varchar(50) DEFAULT NULL,
  `tfn` varchar(50) DEFAULT NULL,
  `estimated_monthly_volume` varchar(255) DEFAULT NULL,
  `use_case_summary` text DEFAULT NULL,
  `corporate_website` varchar(255) DEFAULT NULL,
  `example_messages` text DEFAULT NULL,
  `brand_description` text DEFAULT NULL,
  `help_mt_response` text DEFAULT NULL,
  `opt_out_mt_response` text DEFAULT NULL,
  `opt_in_method` text DEFAULT NULL,
  `is_commercial` tinyint(1) DEFAULT NULL,
  `previous_messaging_service` varchar(255) DEFAULT NULL,
  `previous_content` text DEFAULT NULL,
  `previous_numbers` text DEFAULT NULL,
  `number_published_location` text DEFAULT NULL,
  `is_fortune_1000` tinyint(1) DEFAULT NULL,
  `cta_urls` text DEFAULT NULL,
  `cta_numbers` text DEFAULT NULL,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `global_sender_id_requests_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
